name: Web Automation Workflow

#Triger / Kapan Action-nya jalan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  automation:
    runs-on: ubuntu-latest  # windows-latest, macos-latest, ubuntu-18.04,

    steps:
      - uses: actions/checkout@v3  # Checkout the repository

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'  # Ganti dengan versi Java lain seperti '8', '17'
          distribution: 'temurin'  # Alternatif: 'adoptopenjdk', 'zulu'

      - name: Setup Chrome with extra capabilities
        uses: browser-actions/setup-chrome@v1.4.0
        with:
          chrome-version: latest # Ganti dengan 'stable' untuk versi stabil
          #chrome-options: '--headless' #(Jika ingin menjalankan Chrome dalam mode headless)

      - name: Build with Gradle
        run: |
          chmod +x gradlew  # Make gradlew executable
          ./gradlew build   # Run the build task before tests

      - name: Run Tests
        run: ./gradlew clean test  # Run tests after the build step

      - name: Archive test results
        uses: actions/upload-artifact@v4.3.0
        if: always() #always() # success() , failure(), canceled()
        with:
          name: cucumber reports
          path: reports/cucumber-api-report.html  # Path to test reports
